# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.11

# Chernobyl Scientific Project (CSP) Properties
mod_version = 0.1.0
maven_group = com.ben.csp
archives_base_name = csp-modern

# Fabric API
fabric_version=0.91.0+1.20.1

# Static Analysis Tool Versions
checkstyle_version=10.12.7
pmd_version=6.55.0
spotbugs_version=4.8.3

# AST Parser
javaparser_version=3.25.10
